import "tailwindcss/tailwind.css";
import { Provider } from "react-redux";
import { store } from "../ducks/app/store";
import Layout from "../components/Layout/Layout";
import Head from "next/head";
import { AppProps } from "next/app";

function MyApp({ Component, pageProps }: AppProps) {
  console.log("app.tsx");

  return (
    <Provider store={store}>
      <Head>
        <title>ブログサイト</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </Provider>
  );
}

export default MyApp;
